### ISSUE TITLE
bug: ADDMOD performs operations MOD 2^256

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot#695] opened 2023-08-24 12:26 UTC
# Bug Report

**Kakarot version:** [ee6458a](https://github.com/kkrt-labs/kakarot/commit/ee6458a7089f169334a7dba9665bcc5551507762)

**Current behavior:**
The add mod opcode performs addition of two uint256, without handling the one bit carry returned by the [`uint256_add`](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/common/uint256.cairo#L69). This causes the addition to be performed modulo `2^256`, which shouldn't be the case (see Ethereum yellow paper opcode ADDMOD).

**Expected behavior:**
https://github.com/kkrt-labs/kakarot/blob/ee6458a7089f169334a7dba9665bcc5551507762/src/kakarot/instructions/stop_and_arithmetic_operations.cairo#L320-L333
The add mod opcode should return the operation `(a+b)%c`, without subjecting the intermediate result `a+b` to modulo `2^256`. However, since the bit carry from `uint256_add` isn't used, the operation is performed modulo `2^256`.

**Steps to reproduce:**

- clone ef-tests: https://github.com/kkrt-labs/ef-tests
- generate katana dump of kakarot system and move the .katana folder to your ef-tests directory
- run 
```
RUN_SPECIFIC_TESTS=addmod_d10g0v0_Shanghai cargo test -p ef-testing --features ef-tests -- --nocapture
```
This test will fail due to the incorrect addition performed modulo `2^256`: 
https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/VMTests/vmArithmeticTest/addmodFiller.yml#L109

Indeed, in our case, the performed operation is: (-1 + -2) % 5 = ((0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff + 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe) % 2^256) % 5 = (0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd % 2^256) % 5 = 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd % 5 = 3.

Failing output should be:
```
[!] Case /Users/greg/code/rust/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/VMTests/vmArithmeticTest/addmod.json failed (description: addmod): Test failed: failed test addmod_d10g0v0_Shanghai: expected storage value 0x0000000000000000000000000000000000000000000000000000000000000004, got 0x0000000000000000000000000000000000000000000000000000000000000003
```

**Comment by Eikix** [comment] 2023-09-08 04:06
A duplicate of #678, but let's keep this one, it's more detailed

**Comment by feltroidprime** [comment] 2023-11-30 23:43
can do add mod p in 15 steps for 10 XMR if you want

**Closed** 2024-01-08 17:08 UTC
