### ISSUE TITLE
bug: Origin opcode isn't well tested in test_kakarot.py

### ISSUE THREAD

**Issue by zarboq** [kkrt-labs/kakarot#476] opened 2023-02-02 15:02 UTC
# Bug Report

**Current behavior:**

In `test_kakarot.py` Origin opcode is failing because when executing `kakarot.execute(params).call(caller_address=X)` on contract `get_tx_info()` returns a wrong `TxInfo` which is not initialized well and `account_contract_address` field is 0.

**Expected behavior:**

`account_contract_address` in `TxInfo` should return the caller address

**Steps to reproduce:**

Isolate `ORIGIN` test in `test_cases.py` and run it through `test_kakarot.py`
`TxInfo` is retrieved in `exec_origin()`

Idea to fix it:

Use `MockSigner` (https://github.com/OpenZeppelin/cairo-contracts/blob/main/tests/signers.py#L149) instead of using `Kakarot.execute().call()`

**Comment by dragan2234** [comment] 2023-02-22 01:52
hey @hurrikaanig  i'm interested in taking this

Just to check if my understanding of the issue is correct:

so `ORIGIN` opcode should return origin evm address of the transaction initializer. 

In kakarot that's the end user who is "executing the opcode". So it should return end-users evm address. In our `test_kakarot.py` this transaction is initialized via "kakarot" python object which is a mock "kakarot" contract on starknet.

So for this case "caller_address"  in `execute` method in "contract.py" file is not correctly passed to cairo -- not sure why, but that's how starkware python test library works?


So we can fix it this way: instead of executing method via kakarot.execute() we should call the execute() this way:

```
from utils import MockSigner

PRIVATE_KEY = 123456789987654321
signer = MockSigner(PRIVATE_KEY)
# Then send single transactions with the send_transaction method.


response = await signer.send_transaction(account, contract_address, 'method_name', [])
```
and that response should have the same (or similar) output where we can pull stack and memory data.

**Comment by hurrikaanig** [comment] 2023-02-22 12:35
Yes you're right, not sure if it will work with MockSigner but that's an idea we had. Also you can find example of how it is being used here https://github.com/sayajin-labs/kakarot/blob/90e007133d651d2e62695d9132159553f2604a76/tests/integration/eoa/test_ethaa.py line 80

**Comment by dragan2234** [comment] 2023-02-22 20:28
@ClementWalter Please assign this issue to me.

Regarding using MockSigner, I investigated this, and openzeppelin doesn't provide the python package for this, so I guess we should just copy-paste the code and include it in our repo.

It also uses some nile packages and i couldn't import `cairo-nile` with poetry because it's incompatible with the version of `starknet-dev` package which is 0.3.x and latest version is 0.4.x. Now I saw that in the commit hash above MockSigner is not using nile packages but just wanted to note this, maybe it's possible without nile packages.

Anyway will update later on this when I try more.

one question: should this be implemented for all bytecode tests or only for `ORIGIN` opcode? cc @hurrikaanig

**Comment by ClementWalter** [comment] 2023-02-23 10:13
Actually I don't know if it's possible, once we had this issue we posted on the tg and no one was able to find a solution, not sure if it's the best things to do rn

**Comment by Eikix** [comment] 2023-09-08 03:53
I believe this issue is now re-enabled since our origin refactor #617

**Closed** 2023-10-10 15:23 UTC
Labels: Type: test, Context: isolated
