### ISSUE TITLE
feat: replace `new Uint256` by `Uint256` and `__fp__`

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1273] opened 2024-07-15 19:48 UTC
### Describe the Feature Request

This is 4 steps:

```
func main() {
    tempvar x = Uint256(12, 34);
    let (__fp__, _) = get_fp_and_pc();
    // use &x for Uint256*
    return ();
}
```

while this is 8:

```
func main() {
    tempvar x = new Uint256(12, 34);
    // x is a Uint256*
    return ();
}
```

Overall, using the `new myStruct` calls under the hood `alloc` to allocate a new memory segment and is consequently more expense. This pattern should be avoided when possible.

**Comment by ooochoche** [comment] 2024-07-16 15:32
@ClementWalter I can work on this if it is yet to be assigned to anyone

**Comment by ClementWalter** [comment] 2024-07-16 16:15
@ooochoche thanks for reaching out. Are you a cairo0 / CASM expert ? this may look easy but this is not a beginner friendly issue

**Comment by quentin-abei** [comment] 2024-07-17 02:20
@ClementWalter , i can work on this .

**Comment by quentin-abei** [comment] 2024-07-22 00:08
Hello, please unassign me and give this issue to someone else as all my laptop can't handle all the installations needed to start. Thanks

**Comment by obatirou** [comment] 2024-08-09 10:00
From my understanding, new operator do not allocate a new memory segment but invokes `get_ap` which under the hood calls `get_fp_and_pc();`.
https://github.com/starkware-libs/cairo-lang/blob/0e4dab8a6065d80d1c726394f5d9d23cb451706a/src/starkware/cairo/lang/compiler/preprocessor/preprocessor.py#L1090 

From the [documentation](https://docs.cairo-lang.org/how_cairo_works/object_allocation.html#the-new-operator):
> Note that unlike alloc(), which allocates a new memory segment, the new operator creates the object in the execution segment (see [Segments](https://docs.cairo-lang.org/how_cairo_works/segments.html#segments))

Doing directly `get_fp_and_pc();`, will reduce steps.

**Comment by obatirou** [comment] 2024-08-09 14:28
The error raised when trying to implement the optimisation is:
```
                              code_hash=&code_hash,
E                                          ^*******^
 ap may only be used in an expression of the form [ap + <const>].
E                           tempvar code_hash = Uint256(
E                                   ^*******^
```

This error was already encountered several times and that is when the solution to use `get_ap()` was implemented like here
https://github.com/kkrt-labs/kakarot/blob/7fb90d799a5a0bfab0a48bdfcb4e867d35b4943c/src/kakarot/account.cairo#L149
or here 
https://github.com/kkrt-labs/kakarot/blob/7fb90d799a5a0bfab0a48bdfcb4e867d35b4943c/src/kakarot/interpreter.cairo#L969

**Comment by obatirou** [comment] 2024-08-12 10:05
After a second look and creating a basic reproducing example, the problem is that Cairo cannot retrieve the value of the `ap` register directly. That is why `get_ap()` is necessary.

The error comes from [here](https://github.com/starkware-libs/cairo-lang/blob/0e4dab8a6065d80d1c726394f5d9d23cb451706a/src/starkware/cairo/lang/compiler/preprocessor/compound_expressions.py#L125) in the compiler. From my understanding, `ap` cannot be used directly in a compound expression.

In the Cairo paper (and the [documentation](https://docs.cairo-lang.org/how_cairo_works/functions.html?highlight=register#accessing-the-values-of-the-registers):
> Cairo has no specialized instruction for obtaining the values of the registers
ap, fp, pc. Still, one can retrieve those values and store them in the memory,
using the call 

Hence it makes sense that the `new` keyword calls `get_ap()`

### Basic example
```
%builtins output

from starkware.cairo.common.serialize import serialize_word
from starkware.cairo.common.uint256 import Uint256

func add_one_low(x: Uint256*) -> felt {
    tempvar y = x.low + 1;
    return y;
}

func main{output_ptr: felt*}() {
    tempvar x = Uint256(12, 34);
    let res = cast(ap - 2, Uint256*); 
    tempvar output = add_one_low(res);
    serialize_word(output);
    return ();
}
```

Will fail with 
```
src/tmp_test_compile.cairo:14:34: While expanding the reference 'res' in:
    tempvar output = add_one_low(res);
                                 ^*^
src/tmp_test_compile.cairo:13:20: ap may only be used in an expression of the form [ap + <const>].
    let res = cast(ap - 2, Uint256*);
```

**Comment by obatirou** [comment] 2024-08-13 09:07
To note: it can be more optimized to use locals
```
func main() {
    alloc_locals;
    local x: Uint256 = Uint256(12, 34);
    let fp_and_pc = get_fp_and_pc();
    tempvar __fp__: felt* = fp_and_pc.fp_val;
    // use &x
    return ();
}
```

See https://github.com/kkrt-labs/kakarot/pull/1341/files#r1714939019

**Closed** 2024-08-19 16:56 UTC
